TASK: Migrate Code for Neos 3.0 compatibility
Flowpack/varnish pull request #33
Opened 2017-03-08 16:27 UTC by daniellienert

2017-03-08 17:41 UTC, aertmann requested changes

2017-03-08 17:41 UTC, aertmann commented on Configuration/Settings.yaml
> -    # Log configuration
some comments are lost here due to the automated configuration migration, please adjust manually instead to and only change what's actually needed..

2017-03-08 17:42 UTC, aertmann commented
fixed the travis tests

looks good by reading, thanks for taking care..

just one comment regarding the configuration to be fixed

2017-03-08 17:45 UTC, aertmann commented on Classes/MOC/Varnish/Aspects/ContentCacheAspect.php
> +				$this->logger->log(sprintf('Varnish cache disabled due to uncached path "%s" (can be prevented using "mocVarnishIgnoreUncached")', $evaluateContext['typoScriptPath']), LOG_DEBUG);
whoops, seems like some leftover in the core

2017-03-09 07:44 UTC, daniellienert commented on Classes/MOC/Varnish/Aspects/ContentCacheAspect.php
> +				$this->logger->log(sprintf('Varnish cache disabled due to uncached path "%s" (can be prevented using "mocVarnishIgnoreUncached")', $evaluateContext['typoScriptPath']), LOG_DEBUG);
Yeah, there are a lot of internal leftovers.
So this will break in the future again.

2017-03-09 08:28 UTC, daniellienert commented
Thanks for reviewing @aertmann, comments are fixed.

2017-03-16 22:17 UTC, daniellienert commented
@aertmann - ping?

2017-03-20 18:52 UTC, aertmann approved these changes

2017-03-20 20:20 UTC, merged